# 넘파이

- 넘파이는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지 
- 루프를 사용하지 않고 대량 데이터의 배열

### 넘파이 ndarray 개요

기반 데이터 타입은 ndarray \
넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.

In [9]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])

print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # (2,3) 2개의 행 3개의 열

array3 = np.array([[1,2,3]])
                  

print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [11]:
print(f'array1 : {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')
#ndim은 NumPy 배열의 차원(dimension) 수를 나타내는 속성입니다.

array1 : 1차원, array2: 2차원, array3: 2차원


# ndarray의 데이터 타입

In [159]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(list1, array1, array1.dtype) 

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3] [1 2 3] int32


In [20]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(list2, array2, array2.dtype) # 문자열이 섞여있으면 문자열로 변환 

list3 = [1,2,3.0]
array3 = np.array(list3)
print(list3, array3, array3.dtype) # 실수가 섞여있으면 실수열로 변환  

[1, 2, 'test'] ['1' '2' 'test'] <U11
[1, 2, 3.0] [1. 2. 3.] float64


In [51]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int8')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int8


# ndarray를 편리하게 생성하기 - arange, zeros, ones

In [35]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [41]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.zeros((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)
# 자료형을 설정하지 않으면 자동으로 실수형으로 배정

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


In [47]:
# ndarray
#arrange 는 1차원만 가능, reshape을 쓰면 가능

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [84]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print(array2)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print(array3)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


In [163]:
array1 = np.shape(10)
array4 = array1.reshape(-1,4)

AttributeError: 'tuple' object has no attribute 'reshape'

In [65]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2)) # 3차원 배열
print('array3d:\n', array3d.tolist())

array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:' , array5.shape)

array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:' , array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [68]:
import numpy as np

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start =1, stop =10)
print('array1 :', array1)

value = array1[2]
print('value :', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int32'>


In [74]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [76]:
array1[0] = 9
array1[8] = 0
print('array1 :', array1)


array1 : [9 2 3 4 5 6 7 8 0]


In [80]:
array1d = np.arange(start =1, stop =10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )
     

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


슬라이싱

In [89]:
array1 = np.arange(start =1, stop =10)
array3 = array1[0:3]
print(array3)
print(type(array3))



[1 2 3]
<class 'numpy.ndarray'>


In [91]:
array1 = np.arange(start =1, stop =10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [97]:
array1d = np.arange(start =1, stop =10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:2] \n', array2d[1:3, 0:2])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:2] 
 [[4 5]
 [7 8]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [99]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape :',array2d[0].shape,'array2d[1] shape :',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape : (3,) array2d[1] shape : (3,)


In [101]:
# tolist 자료형을 리스트로 변환
#[0,1] 0행 1행을 선택

array1d = np.arange(start =1, stop =10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ' , array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ' , array4.tolist())

array5= array2d[[0,1]]
print('array2d[[0,1]] => ' , array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱 
- 조건필터링과 검색을 동시에 할 수있기 때문에 매우 자주 사용되는 인덱싱 방식

In [112]:
array1d = np.arange(start =1, stop =10)

array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값 :',array3 )

array1d>5 불린 인덱싱 결과 값 : [6 7 8 9]


In [114]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [118]:
#true 부분만 나온다

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱싱 필터링 결과 :',array3 )

array1d>5 불린 인덱싱 필터링 결과 : [6 7 8 9]


In [120]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱싱 필터링 결과 :',array4 )

일반 인덱싱 필터링 결과 : [6 7 8 9]


In [122]:
# 행렬의 정렬 - sort()와 argsort()

In [128]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

sort_array1 = np.sort(org_array)
print(' np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print(' np.sort() 호출 후 원본 정렬', org_array)

sort_array1 = org_array.sort()
print(' np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)

원본 행렬: [3 1 9 5]
 np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
 np.sort() 호출 후 원본 정렬 [3 1 9 5]
 np.sort() 호출 후 반환된 정렬 행렬: None


In [130]:
# 억순으로 출력하고 싶을 때 [::-1]를 추가
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [134]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [136]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [142]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [151]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과 :\n', dot_product)

행렬 내적 결과 :
 [[ 58  64]
 [139 154]]


In [153]:
# 전치행렬

A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬 :\n',transpose_mat)

A의 전치 행렬 :
 [[1 3]
 [2 4]]
