#[step 1] 데이터 준비 / 기본 설정

In [108]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

In [110]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [112]:
# 난 값이 많은 deck 열을 삭제, embarked 와 내용이 겹치는 embark_town 삭제
rdf = df.drop(['deck','embark_town'], axis=1)
rdf.columns.values

array(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'alive', 'alone'],
      dtype=object)

In [114]:
rdf = df.dropna(subset=['age'], how='any', axis=0)
rdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     714 non-null    int64   
 1   pclass       714 non-null    int64   
 2   sex          714 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        714 non-null    int64   
 5   parch        714 non-null    int64   
 6   fare         714 non-null    float64 
 7   embarked     712 non-null    object  
 8   class        714 non-null    category
 9   who          714 non-null    object  
 10  adult_male   714 non-null    bool    
 11  deck         184 non-null    category
 12  embark_town  712 non-null    object  
 13  alive        714 non-null    object  
 14  alone        714 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 70.2+ KB


In [116]:
# knn은 scale 에 민감하다 s c q nan 이 0 1 2 3 이라고 해서 0 이 작은게 아님
rdf ['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [118]:
rdf ['embarked'].value_counts()

embarked
S    554
C    130
Q     28
Name: count, dtype: int64

In [120]:
most_freq = rdf ['embarked'].value_counts().idxmax()
most_freq

'S'

In [122]:
rdf ['embarked'].fillna(most_freq, inplace = True)

C:\Users\705-8\AppData\Local\Temp\ipykernel_524\4171624962.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rdf ['embarked'].fillna(most_freq, inplace = True)
C:\Users\705-8\AppData\Local\Temp\ipykernel_524\4171624962.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rdf ['embarked'].fillna(most_freq, inplace = True)


In [124]:
df.describe(include='all')

survived      pclass   sex         age       sibsp       parch  \
count   891.000000  891.000000   891  714.000000  891.000000  891.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   577         NaN         NaN         NaN   
mean      0.383838    2.308642   NaN   29.699118    0.523008    0.381594   
std       0.486592    0.836071   NaN   14.526497    1.102743    0.806057   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    2.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    3.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    0.000000   
max       1.000000    3.000000   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [126]:
# min max 가 다 다르니까 scale을 해줘야겠구나 하고 생각

# 분석에 사용할 속성을 선택

In [129]:
ndf = rdf[['survived','pclass','sex','age','sibsp','parch','embarked']]
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [131]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  714 non-null    int64  
 1   pclass    714 non-null    int64  
 2   sex       714 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     714 non-null    int64  
 5   parch     714 non-null    int64  
 6   embarked  714 non-null    object 
dtypes: float64(1), int64(4), object(2)
memory usage: 44.6+ KB


In [133]:
# pclass도 범주형 성별 찹승도시 원핫인코딩 해줘야함, 성별은 이진, 하고나서 하나의 특성을 없애주는 것도 맞겠다

In [135]:
onehot_sex = pd.get_dummies(ndf['sex']).astype(int) # 처음에 TF로 나오는데 이걸 astype 해주면 된다
#ndf의 'sex' 열에 대해 원-핫 인코딩을 수행합니다. 이는 'sex' 열의 고유한 값(예: 'male', 'female')에 대해 각각의 값을 열로
# 변환하고, 해당 값이 존재하는 경우 1, 그렇지 않은 경우 0으로 표시합
onehot_sex.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [137]:
ndf = pd.concat([ndf, onehot_sex], axis =1)
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked  female  male
0         0       3    male  22.0      1      0        S       0     1
1         1       1  female  38.0      1      0        C       1     0
2         1       3  female  26.0      0      0        S       1     0
3         1       1  female  35.0      1      0        S       1     0
4         0       3    male  35.0      0      0        S       0     1

In [139]:
onegot_embarked = pd.get_dummies(ndf['embarked'],prefix ='town').astype('int')
onegot_embarked.head()

town_C  town_Q  town_S
0       0       0       1
1       1       0       0
2       0       0       1
3       0       0       1
4       0       0       1

In [141]:
ndf = pd.concat([ndf, onegot_embarked], axis =1)
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked  female  male  \
0         0       3    male  22.0      1      0        S       0     1   
1         1       1  female  38.0      1      0        C       1     0   
2         1       3  female  26.0      0      0        S       1     0   
3         1       1  female  35.0      1      0        S       1     0   
4         0       3    male  35.0      0      0        S       0     1   

   town_C  town_Q  town_S  
0       0       0       1  
1       1       0       0  
2       0       0       1  
3       0       0       1  
4       0       0       1

In [143]:
ndf.drop(['sex','embarked','male'], axis =1, inplace =True)
ndf.head()

survived  pclass   age  sibsp  parch  female  town_C  town_Q  town_S
0         0       3  22.0      1      0       0       0       0       1
1         1       1  38.0      1      0       1       1       0       0
2         1       3  26.0      0      0       1       0       0       1
3         1       1  35.0      1      0       1       0       0       1
4         0       3  35.0      0      0       0       0       0       1

# 데이터 셋 구분 - 훈련용 train data/ 검증용 test data

In [146]:
X=ndf[list(ndf.columns)[1:]] # 독립 변수 x
y=ndf[list(ndf.columns)[0]]

In [148]:
X.shape

(714, 8)

In [150]:
y.shape

(714,)

In [152]:
X.head()

pclass   age  sibsp  parch  female  town_C  town_Q  town_S
0       3  22.0      1      0       0       0       0       1
1       1  38.0      1      0       1       1       0       0
2       3  26.0      0      0       1       0       0       1
3       1  35.0      1      0       1       0       0       1
4       3  35.0      0      0       0       0       0       1

In [162]:
# 특성 정규화
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit(X).transform(X)

In [166]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3, random_state=10)

In [168]:
print('train data 개수: ', X_train.shape)
print('test data 개수: ', X_test.shape)

train data 개수:  (499, 8)
test data 개수:  (215, 8)


In [170]:
print('y_train data 개수: ', y_train.shape)
print('y_test data 개수: ', y_test.shape)

y_train data 개수:  (499,)
y_test data 개수:  (215,)


In [172]:
from sklearn.neighbors import KNeighborsClassifier

# 모형 객체 생성(k=5 생성)
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)


KNeighborsClassifier()

In [174]:
# 학습을 다 했으면 평가를 해야함

In [176]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve

def get_clf_eval(y_test=None , pred = None): # 여기는 우리가 만든거
    confusion = confusion_matrix(y_test , pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)

    roc_auc = roc_auc_score(y_test, pred)
    print ('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도 : {0: .4f}, 정밀도 : {1:.4f}, 재현율 : {2:.4f},\
          F1:{3:.4f}, AUC:{4:.4f}'.format(accuracy,precision, recall, f1, roc_auc))

In [178]:
y_hat = knn.predict(X_test)

In [180]:
get_clf_eval(y_test,y_hat)

오차 행렬
[[110  15]
 [ 24  66]]
정확도 :  0.8186, 정밀도 : 0.8148, 재현율 : 0.7333,          F1:0.7719, AUC:0.8067


In [184]:
y_hat[:10]

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [186]:
import numpy as np
y_test = np.array(y_test)
y_test[:10]

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [190]:
from sklearn.metrics import classification_report
# 모형 성능 평가 - 평가지표 개선
knn_report = classification_report(y_test, y_hat)
print(knn_report)

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       125
           1       0.81      0.73      0.77        90

    accuracy                           0.82       215
   macro avg       0.82      0.81      0.81       215
weighted avg       0.82      0.82      0.82       215



In [192]:
# 인접한 k 개의 sample에 대해 거리와 index를 반환
knn.kneighbors()

(array([[2.90414419, 3.03676623, 3.26298986, 3.41669105, 3.42425914],
        [0.        , 0.06888798, 0.06888798, 0.06888798, 0.06888798],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        ...,
        [0.        , 0.06888798, 0.06888798, 0.06888798, 0.13777595],
        [0.96443168, 1.22229197, 1.22229197, 1.22229197, 1.24207642],
        [1.2434624 , 1.29579097, 1.51838311, 1.51838311, 1.51838311]]),
 array([[246, 142, 297,  89, 427],
        [ 49, 209,  25,  77, 258],
        [ 59, 339, 256,  13, 320],
        ...,
        [216,  75, 274,  54,  19],
        [486,   9, 172, 208, 360],
        [368, 277, 426,  84, 447]], dtype=int64))

In [194]:
# svm분류 모델 - sklearn 사용

In [196]:
# skleran 라이브러리에서 svm 분류 모형 가져오기 
from sklearn import svm
# 모형 객체 생성 (기본값 커널=rbf' 적용)
svm_model = svm.SVC(C=2.0, gamma = 0.2)
# train data를 가지고 모형 학습
svm_model.fit(X_train,y_train)

SVC(C=2.0, gamma=0.2)

In [198]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve

def get_clf_eval(y_test=None , pred = None): # 여기는 우리가 만든거
    confusion = confusion_matrix(y_test , pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)

    roc_auc = roc_auc_score(y_test, pred)
    print ('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도 : {0: .4f}, 정밀도 : {1:.4f}, 재현율 : {2:.4f},\
          F1:{3:.4f}, AUC:{4:.4f}'.format(accuracy,precision, recall, f1, roc_auc))

In [208]:
y_hat = svm_model.predict(X_test)

In [210]:
get_clf_eval(y_test,y_hat)

오차 행렬
[[120   5]
 [ 33  57]]
정확도 :  0.8233, 정밀도 : 0.9194, 재현율 : 0.6333,          F1:0.7500, AUC:0.7967


In [212]:
y_hat[:10]

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [214]:
import numpy as np
y_test = np.array(y_test)
y_test[:10]

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [218]:
from sklearn.metrics import classification_report
# 모형 성능 평가 - 평가지표 개선
svm_model = classification_report(y_test, y_hat)
print(knn_report)

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       125
           1       0.81      0.73      0.77        90

    accuracy                           0.82       215
   macro avg       0.82      0.81      0.81       215
weighted avg       0.82      0.82      0.82       215

